### ISSUE TITLE
"require is not defined" after update to karma-electron 7 / electron 12

### ISSUE THREAD

**Issue by trusktr** [twolfson/karma-electron#53]
Tooling is always tricky business. This is what I have in my config:

```js
		browsers: ['CustomElectron'],
		customLaunchers: {
			CustomElectron: {
				base: 'Electron',
				flags: [ '--show' ]

				browserWindowOptions: {
					nodeIntegration: true,
					nodeIntegrationInWorker: true,
					nodeIntegrationInSubFrames: true,
					contextIsolation: false,
				},
			},
		},
		
		preprocessors: {
			'dist/**/*.test.js': ['electron', 'webpack', 'sourcemap'],
		},

		client: {
			useIframe: false,
			loadScriptsViaRequire: false, // true makes no difference.
		},
```

Did I miss something in the newer karma-electron?

**Comment by twolfson** [comment]
That all looks good to me =/ We run our tests against these versions so it should just work. Sanity check: Have you upgraded to the latest `karma-electron` as well? =/

**Comment by trusktr** [comment]
I wonder if maybe it's a side-effect of karma-webpack. The new karma-webpack has an optimization that splits common dependencies into a shared module (the older version made a big bundle for every test file, each bundle having duplicates). This is what one test file looks like:

```js
// /absoluteElementOperations.test.2135415586.js
"use strict";
(self["webpackChunklume"] = self["webpackChunklume"] || []).push([["ElementOperations.test.2135415586"],{},
/******/ __webpack_require__ => { // webpackRuntimeModules
/******/ var __webpack_exec__ = (moduleId) => (__webpack_require__(__webpack_require__.s = moduleId))
/******/ __webpack_require__.O(0, ["commons"], () => (__webpack_exec__("./dist/core/ElementOperations.test.js")));
/******/ var __webpack_exports__ = __webpack_require__.O();
/******/ module.exports = __webpack_exports__;
/******/ }
]);
```

It is loaded in the karma's html entrypoint like this:

```html
<script type="text/javascript" src="/absoluteElementOperations.test.2135415586.js" crossorigin="anonymous"></script>
```

and it gives `module is not defined` on `module.exports`.

hm. :thinking:

**Comment by twolfson** [comment]
Yea, using `webpack` to define its own `require/import` while also expecting Electron/Node.js' `require` to just work seems like a big headache to wrangle x_x

**Comment by trusktr** [comment]
Hmm. If I try `process.versions` in console, I get `process is not defined`. Maybe the `browserWindowOptions` aren't taking effect like I'm expecting?

**Comment by trusktr** [comment]
I am baffled. I edited `node_modules/karma-electron/lib/electron-launcher.js` and I have this:

```js
  console.log('$$$$$$$$$$$$$$$$ BROWSER WINDOW OPTIONS', browserWindowOptions)
  process.exit(456)
  var browserWindow = new BrowserWindow(browserWindowOptions);
```

`process.exit` is needed otherwise this output won't show up in console. I see this is what is passed to `BrowserWindow`:

```
15 09 2021 12:49:55.886:ERROR [launcher]: Cannot start Electron

15 09 2021 12:49:55.887:ERROR [launcher]: Electron stdout: $$$$$$$$$$$$$$$$ BROWSER WINDOW OPTIONS {
  show: false,
  nodeIntegration: true,
  nodeIntegrationInWorker: true,
  nodeIntegrationInSubFrames: true,
  contextIsolation: false,
  webPreferences: { nativeWindowOpen: true }
}

15 09 2021 12:49:55.887:ERROR [launcher]: Electron stderr: 
```

But for whatever reason, there simply are no Node.js APIs that my tests can access.

**Comment by trusktr** [comment]
Regardless if I set `browserWindowOptions.show` to `true` or `false`, and window always pops up. Seems that something isn't working as expected, but no idea what yet.

**Comment by trusktr** [comment]
Hm, something strange is that my tests seem to run twice: first time I see all their output from the reporter formatter, then after all this output I see all the `require is not defined` or `module is not defined` output from all those files. Hmmmm :thinking:

**Comment by trusktr** [comment]
This is my files array:

```js
files: [
	path.resolve(__dirname, 'karma-augment-node-path.js'),
	path.resolve(__dirname, 'karma-globalThis.js'),
	{pattern: 'dist/**/*.test.js', watched: false},
],
```

This result in `karma-augment-node-path.js` being the very first script that runs, containing this:

```js
const path = require('path') // ReferenceError: require is not defined
process.env.NODE_PATH = path.resolve(process.cwd(), 'node_modules') + ':' + process.env.NODE_PATH
require('module').Module._initPaths()
```

and that results in the first error being from that file:

```
Electron 12.0.18 (Node 14.16.0) ERROR
  An error was thrown in afterAll
  ReferenceError: require is not defined
      at /home/trusktr/src/lume+lume/packages/cli/config/karma-augment-node-path.js:12:14
...
```

followed by all the other similar errors. However that is line 7 in my source, but the error states it to be line 12. Still investigating...

**Comment by trusktr** [comment]
Sorry for the noise. Writing things down while I investigate.

I added `console.log(document.documentElement.outerHTML)` as the first line in my first file (`karma-augment-node-path.js`), at that point this is what the document looks like:

<details><summary>html</summary>

```html
<html>
	<head>
		<title></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
	</head>
	<body>
		<!-- The scripts need to be in the body DOM element, as some test running frameworks need the body
       to have already been created so they can insert their magic into it. For example, if loaded
       before body, Angular Scenario test framework fails to find the body and crashes and burns in
       an epic manner. -->
		<script src="context.js"></script>
		<script type="text/javascript">
			// Configure our Karma and set up bindings
			window.__karma__.config = {
				args: [],
				useIframe: false,
				runInParent: false,
				captureConsole: true,
				clearContext: true,
				loadScriptsViaRequire: true,
				originalArgs: [],
			}

			window.__karma__.setupContext(window)

			// All served files with the latest timestamps
			window.__karma__.files = {
				'/absolute/tmp/_karma_webpack_908800/runtime.js': 'd02143f912cdddb6d952f6443e60fd9503e17d78',
				'/absolute/tmp/_karma_webpack_908800/commons.js': 'e4e97b2020fe20a1a3396a74735dbac110104f1b',
				'/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/jasmine-core/lib/jasmine-core/jasmine.js':
					'51a40acf5239b7ae03a061e37e3ae2715d0199de',
				'/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/karma-jasmine/lib/boot.js':
					'945a38bf4e45ad2770eb94868231905a04a0bd3e',
				'/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/karma-jasmine/lib/adapter.js':
					'6cf71867f538f40db053c1775b2c56a83696375c',
				'/absolute/home/trusktr/src/lume+lume/packages/cli/config/karma-augment-node-path.js':
					'28fb8f134be6b6e2a3b689018539c814d2fce0d8',
				'/absolute/home/trusktr/src/lume+lume/packages/cli/config/karma-globalThis.js':
					'1c6e026a24b2446d6424582e6d372f4ca2288ab2',
				'/absoluteElementOperations.test.2135415586.js': '635255d9f307355f9888f887d0c36dce1a05348c',
				'/absoluteNode.test.3975508984.js': 'a43db610f1d0fc66ae1ff90b7043d5c63b816ffd',
				'/absoluteScene.test.2885136436.js': 'e6f01df70320790fba580c570004d2ba629a1e5b',
				'/absoluteTreeNode.test.2100951490.js': '279f5fea933983f820719b7da3bd7f71d19cb6a0',
				'/absoluteXYZNonNegativeValues.test.667048693.js': '23827232145b0e9ea3979ecbe2545f561022c1c0',
				'/absoluteXYZNumberValues.test.2135002697.js': '018448bd88263573fb56ed6c863680252fa2517d',
				'/absoluteXYZSizeModeValues.test.1176671807.js': '2fcf1b01e7fdcf3bb7541a4212dba1dbbbdee3fb',
				'/absoluteXYZStringValues.test.3306457786.js': 'a4de163308cf205257b34a65dc75319bf32810a6',
				'/absoluteXYZValues.test.4115611540.js': '97479f89503ddb7660b2603107637824b05d35a6',
				'/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/stacktrace-js/dist/stacktrace.min.js':
					'96d5520ba4a89e55a05fc45877a11236015ad4d1',
				'/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/stacktrace-js/dist/stacktrace.min.js.map':
					'c7b3d5166813a99f50a38dbf334813e06d7120b8',
				'/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/karma-stacktrace/lib/stacktrace.js':
					'6235c3ac9372ae70c9269346b0460d87d32fd0ab',
			}
		</script>
		<!-- Dynamically replaced with <script> tags -->
		<script
			type="text/javascript"
			src="/absolute/tmp/_karma_webpack_908800/runtime.js?d02143f912cdddb6d952f6443e60fd9503e17d78"
			crossorigin="anonymous"
		></script>
		<script
			type="text/javascript"
			src="/absolute/tmp/_karma_webpack_908800/commons.js?e4e97b2020fe20a1a3396a74735dbac110104f1b"
			crossorigin="anonymous"
		></script>
		<script
			type="text/javascript"
			src="/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?51a40acf5239b7ae03a061e37e3ae2715d0199de"
			crossorigin="anonymous"
		></script>
		<script
			type="text/javascript"
			src="/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/karma-jasmine/lib/boot.js?945a38bf4e45ad2770eb94868231905a04a0bd3e"
			crossorigin="anonymous"
		></script>
		<script
			type="text/javascript"
			src="/absolute/home/trusktr/src/lume+lume/packages/cli/node_modules/karma-jasmine/lib/adapter.js?6cf71867f538f40db053c1775b2c56a83696375c"
			crossorigin="anonymous"
		></script>
		<script
			type="text/javascript"
			src="/absolute/home/trusktr/src/lume+lume/packages/cli/config/karma-augment-node-path.js?28fb8f134be6b6e2a3b689018539c814d2fce0d8"
			crossorigin="anonymous"
		></script>
	</body>
</html>
```

</details>

At the end of the document is the script tag that has my console.log statement. This script tag has just been injected into the page, and that's when the console.log runs.

Is there something missing there? Do script tags need an attribute or something to make them have Node APIs?

**Comment by trusktr** [comment]
I set `customDebugFile` to my own HTML file, where I modified `debug.html` from Karma to add a `console.log(require)` and `require` is just not there.

<details>
<summary>debug.html
</summary>

```html
<!DOCTYPE html>
<!--
This is the execution context.
Loaded within the iframe.
Reloaded before every execution run.
-->
<html>
<head>
  <title></title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
</head>
<body>
  <!-- The scripts need to be in the body DOM element, as some test running frameworks need the body
       to have already been created so they can insert their magic into it. For example, if loaded
       before body, Angular Scenario test framework fails to find the body and crashes and burns in
       an epic manner. -->
  <script src="context.js"></script>
  <script type="text/javascript">
	console.log(require) // <!------------------------------------------- require is not defined
	debugger
    // Configure our Karma and set up bindings
    %CLIENT_CONFIG%
    window.__karma__.setupContext(window);

    // All served files with the latest timestamps
    %MAPPINGS%
  </script>
  <!-- Dynamically replaced with <script> tags -->
  %SCRIPTS%
  <!-- Since %SCRIPTS% might include modules, the `loaded()` call needs to be in a module too.
   This ensures all the tests will have been declared before karma tries to run them. -->
  <script type="module">
    window.__karma__.loaded();
  </script>
  <script nomodule>
    window.__karma__.loaded();
  </script>
</body>
</html>
```

</details>

I haven't had this issue until upgrading from karma-electron ^6.0.0 to ^7.0.0 just the other day. I haven't upgraded `karma` itself though.

**Comment by trusktr** [comment]
Huh, interesting. I just updated `karm` from 4.1.0 to 6.3.4, and the `require is not defined` errors are not happening (for now, at least) and now I have a different error:

```
Electron 12.0.2 (Node 14.16.0) ERROR
  An error was thrown in afterAll
  Uncaught SyntaxError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL 'undefined' is invalid. thrown
```

and I'm not using any workers in my tests.

What a can of worms!

**Comment by trusktr** [comment]
Oh.. My.. Goodness... those above options have to be inside the `webPreferences` object. Doh!

```js
				browserWindowOptions: {
					webPreferences: {
						nodeIntegration: true,
						nodeIntegrationInWorker: true,
						nodeIntegrationInSubFrames: true,
						contextIsolation: false,
					}
				},
```

It's all working smoothly now (but still with Webpack, and the output as CommonJS).

**Comment by trusktr** [comment]
I still keep getting these errors, but only in debug mode with a window open, regardless if I have the proper config.

In "debug mode" I set `singleRun` to `false`, and `browserWindowOptions.show` to `true`. In this mode, even if `client.loadScriptsViaRequire` is `true`, I get `require is not defined`.

When I run tests without debug mode enabled, `console.log` statements that come after any `require()` call show up in the terminal output just fine. It just isn't working in the debug window.

Any ideas?

**Comment by twolfson** [comment]
Shot in the dark: It sounds like something in your `singleRun: false` is messing with you (e.g. test environment isn't properly being cleaned, or maybe something is overzealously removing `require`)

**Comment by trusktr** [comment]
Hmm. Yeah, no idea why something would be different. This is the first file I have in `files`:

```js
// karma-augment-node-path.js
const path = require('path')
process.env.NODE_PATH = path.resolve(process.cwd(), 'node_modules') + ':' + process.env.NODE_PATH
require('module').Module._initPaths()
console.log('################################################################')
console.log('################################################################')
console.log('################################################################')
console.log('################################################################')
console.log('################################################################')
```

When I run with `singleRun: true`, I see this in my terminal output:

```
...
22 09 2021 12:17:20.242:INFO [launcher]: Starting browser Electron
22 09 2021 12:17:20.669:INFO [Electron 14.0.1 (Node 14.17.0)]: Connected on socket eMIRJxV7RjNPNWytAAAB with id 67478283
Electron 14.0.1 (Node 14.17.0) LOG LOG: '################################################################'
Electron 14.0.1 (Node 14.17.0) LOG LOG: '################################################################'
Electron 14.0.1 (Node 14.17.0) LOG LOG: '################################################################'
Electron 14.0.1 (Node 14.17.0) LOG LOG: '################################################################'
Electron 14.0.1 (Node 14.17.0) LOG LOG: '################################################################'
...
```

When I run with `singleRun: false`, I see this in my terminal, and similar in Electron console (just the require errors, not the other terminal output):

```
...
22 09 2021 12:28:40.750:INFO [launcher]: Starting browser Electron
22 09 2021 12:28:41.220:INFO [Electron 14.0.1 (Node 14.17.0)]: Connected on socket 8PCN10VDBPVkc12tAAAB with id 6745101
22 09 2021 12:28:56.969:WARN [Electron 14.0.1 (Node 14.17.0)]: Disconnected (0 times) Client disconnected from CONNECTED state (transport close)
Electron 14.0.1 (Node 14.17.0) ERROR
  Disconnected Client disconnected from CONNECTED state (transport close)
22 09 2021 12:28:57.046:INFO [Electron 14.0.1 (Node 14.17.0)]: Connected on socket v_9MI5_w9DYWsB0dAAAD with id 6745101
Electron 14.0.1 (Node 14.17.0) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: require is not defined
  ReferenceError: require is not defined
      at /home/trusktr/src/lume+lume/packages/cli/config/karma-augment-node-path.js:2:14
...
```

May the disconnected error have to do with it? I think that's just the open/refreshing of the debug window, right?

**Comment by trusktr** [comment]
I confirm the only difference in my config is `singleRun:true` (working) vs `singleRun:false` (not working).

**Comment by trusktr** [comment]
Ok, I found a clue, but not sure what it points to.

I noticed that when I first open the debug window and subsequently open the console, I see the expected `######...` output and no `require is not defined` errors.

It is only _after I refresh_ the debug window that the errors happen. All subsequent runs after the first have the error.

This explains why when `singleRun` is `true` the tests pass and the whole process exits with `0`; because the first run is always fine.

The combination of my mistake, plus the fact that refreshing the Electron breaks it, totally did not help because no matter what options I tried, even if they were correct, things continued to not work.

The question is, why are `require` and friends not available _after refresh_ of the Electron window? This seems like an Electron bug.

**Comment by trusktr** [comment]
(No luck updating from Electron 14.0.1 to 15.0.0. Electron 15 completely crashes on any refresh attempt with devtools saying `DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect.`)

**Comment by trusktr** [comment]
^ I think the issue is in Electron itself: karma-electron has launched Electron using `new BrowserWindow` like normal, and it even all works fine on first run, but then a refresh of the window causes Node APIs (`require`, `module`, etc) to be `is not defined`.

I don't think there is any possible option that `karma-electron` could define that would cause Electron to disable Node integration upon refresh of an Electron window. I don't think there is any such Electron option for that behavior. Something seems wrong in Electron.

**Comment by twolfson** [comment]
Now that we discovered `setWindowOpenHandler` wasn't set so settings didn't propagate (#54), it might be worth trying out `7.1.0` to see if this fixes it. Though, I'm doubtful since our tests still didn't raise any issues =/
